### ISSUE TITLE
Creation Kit updated, needs emergency update. (Skyrim)

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#78]
The Creation Kit for Skyrim SE just updated and CKPE needs a new patch. I'm unable to use the patches now, and I have to wait for an update. This probably needs prioritized. 😓

**Comment by CSec0ps** [comment]
Same here, and now I'm forced to use the vanilla CK until there's patch. It's true what they say, you don't know what you have until it's gone

**Comment by yak3d** [comment]
I think this was fixed in `cf83275ab3e63b7adff93a9a1444cb2789285f14`. You can find the build here: https://github.com/Perchik71/Creation-Kit-Platform-Extended/actions/runs/11983463498

**Comment by CSec0ps** [comment]
I did run a build after this commit but I was still getting an immediate crash after launching the CK. Maybe there are more commits needed to fix this

**Comment by robertgk2017** [comment]
There has not been any commits made to update for the latest CK.

**Comment by yak3d** [comment]
> There has not been any commits made to update for the latest CK.

Is 1378 not the latest version? https://github.com/Perchik71/Creation-Kit-Platform-Extended/commit/cf83275ab3e63b7adff93a9a1444cb2789285f14

**Comment by robertgk2017** [comment]
1378 is the latest CK, but there have been no commits to CKPE to actually support it.

**Comment by yak3d** [comment]
Ah my bad!

**Comment by Perchik71** [comment]
![2024-11-25_11-46-02](https://github.com/user-attachments/assets/c5e451d5-7bf6-4b9c-9223-d5a59bcfc9d9)
unstable, so try, CTD can be anywhere.

**Comment by CSec0ps** [comment]
Going to give this a test in a second :-)

**Comment by CSec0ps** [comment]
Perfect, this is working for me now. I'll be using the CK quite a bit today so I will let you know if I hit any issues, or CTD

**Comment by CSec0ps** [comment]
Actually.. I have just had it crash on me while trying to load an exterior cell. Is the crash dump file of use to you? If so I can send it across

![image](https://github.com/user-attachments/assets/08942338-2aa8-4f3c-98a9-39db0b75f4dd)

**Comment by Khitiara** [comment]
id been having that same crash on exteriors a bunch before the creation kit upgrade too for what thats worth

**Comment by CSec0ps** [comment]
This is working better, but I'm still hitting Fatal Errors with this build. I can now load interior cells, but if I try to load an exterior cell it crashes. I loaded only **skyrim.esm**, and then tried to load the **RiftenCitySouth** cell of the **RiftenWorld** space. This caused a crash. If you load this cell, does it work for you or crash? 

![image](https://github.com/user-attachments/assets/32d96e8a-76ee-4afe-91f9-288c95c29217)

**Comment by Perchik71** [comment]
![2024-11-26_00-12-07](https://github.com/user-attachments/assets/3bfb5c7b-601b-4de5-87c3-05c4b7cbbc61)
When updating, I focus on the original data. Vanilla opened, everything else is already nuances.

**Comment by CSec0ps** [comment]
Ahh, interesting. No problem, must be something on my side then :-)
